openapi: '3.0.3'

info:
  description: concentrate.ai take home quiz
  version: 0.2.0
  title: Quiz

servers:
- url: http://localhost:3010/api/v0

paths:
  /users/by-email:
    get:
      summary: Get user by email
      parameters:
      - in: query
        name: email
        schema:
          type: string
        required: true
        description: Email of the user to retrieve
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    put:
      summary: Upsert user JSON by email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserData'
      responses:
        '200':
          description: User upserted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string

    UserData:
      type: object
      properties:
        email:
          type: string
        name:
          type: string