version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_app
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
      AZURE_AD_TENANT_ID: ${AZURE_AD_TENANT_ID}
      FRONTEND_URL: http://localhost:3000

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - REACT_APP_AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
      - REACT_APP_AZURE_AD_REDIRECT_URI=http://localhost:3000
      - REACT_APP_BACKEND_URL=http://localhost:4000

volumes:
  postgres_data:
